on:
  push:
    branches:
      - main

name: Development

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: buildx
        name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker buildx build --no-cache --push \
            --platform ${{ steps.buildx.outputs.platforms }} \
            --tag ghcr.io/$GITHUB_ACTOR/expressvpn-pod-gateway:dev \
            --tag ghcr.io/$GITHUB_ACTOR/expressvpn-pod-gateway:dev-$(echo $GITHUB_SHA | head -c7) \
            .
